FROM registry.suse.com/bci/python:3.13

WORKDIR /app
MAINTAINER SLES16 Student <student@suse.test> 

LABEL name="yq image" \
  maintainer="student _AT_ suse.test" \
  vendor="Risu" \
  version="1.0.0" \
  release="1" \
  summary="yq execution container" \
  description="Runs yq"

ENV USER_NAME=risu \
  USER_UID=10001 \
  LC_ALL=en_US.utf8

RUN pip install --upgrade pip --no-cache-dir && \
    pip install --upgrade yq --no-cache-dir

USER 10001
VOLUME /data
ENTRYPOINT ["/usr/local/bin/yq"]
CMD ["-h"]
